package com.myspace.p2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class p2a1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public p2a1() {
    }




}